accounts/urls.py
from django.urls import path, include
from .views import UserRegistrationView, UserLoginView, UserLogoutView, UserBankAccountUpdateView, UserPasswordChangeView
urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name="register"),
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
    path('change-password/', UserPasswordChangeView.as_view(),
         name="change_password"),
    path('profile/', UserBankAccountUpdateView.as_view(), name="profile")
]

mamar_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomePageView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="homepage"),
    path('accounts/', include("accounts.urls")),
    path('transactions/', include("transactions.urls")),
]

transactions/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawalMoneyView, LoanMoneyView, LoanListView, TransactionReportView, PayLoanView, SendMoneyView

urlpatterns = [
    path('deposit/', DepositMoneyView.as_view(), name="deposit_money"),
    path('withdraw/', WithdrawalMoneyView.as_view(), name="withdrawal_money"),
    path('report/', TransactionReportView.as_view(), name="transaction_report"),
    path('send_money/', SendMoneyView.as_view(), name="send_money"),
    path('loan_request/', LoanMoneyView.as_view(), name="loan_request"),
    path('loans/', LoanListView.as_view(), name="loan_list"),
    path('loan/<int:loan_id>/', PayLoanView.as_view(), name="pay_loan"),
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .contants import TRANSACTION_TYPE
# Create your models here.


class Transactions(models.Model):
    account = models.ForeignKey(
        UserBankAccount, related_name='transactions', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    balance_after_transaction = models.DecimalField(
        max_digits=12, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approval = models.BooleanField(default=False)
    is_bank_bankrupt = models.BooleanField(
        default=False, null=True, blank=True)

    class Meta:
        ordering = ['timestamp']

transactions/forms.py
from typing import Any
from django import forms
from .models import Transactions
from accounts.models import UserBankAccount


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ['amount', 'transaction_type']

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class SendMoneyForm(TransactionForm):
    account_no = forms.IntegerField()

    class Meta:
        model = Transactions
        fields = ['amount', 'transaction_type']

    def clean_account_no(self):
        account_no = self.cleaned_data['account_no']
        account = UserBankAccount.objects.filter(
            account_no=account_no).exists()
        if not account:
            raise forms.ValidationError(
                f"User with account {account_no} does not exist")
        return account_no

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount > self.account.balance:
            raise forms.ValidationError(f"You don't have enough money")
        return amount


class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit = 1000
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit:
            raise forms.ValidationError(
                f"Minimum deposit amount is {min_deposit}"
            )
        return amount


class WithdrawalForm(TransactionForm):
    def clean_amount(self):
        account = self.account
        min_withdrawal = 500
        max_withdrawal = 10000
        balance = account.balance
        amount = self.cleaned_data.get('amount')

        if amount < min_withdrawal:
            raise forms.ValidationError(
                f"Minimum withdraw amount is {min_withdrawal}"
            )
        elif amount > max_withdrawal:
            raise forms.ValidationError(
                f"Maximum withdraw amount is {max_withdrawal}"
            )
        elif amount > balance:
            raise forms.ValidationError(
                f"Not sufficient balance. Available balance {balance}"
            )

        return amount


class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data["amount"]
        return amount

transactions/views.py
from typing import Any
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.views import View
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from core.models import Bank
# from django.core.mail import EmailMultiAlternatives
# from django.template.loader import render_to_string
from .models import Transactions
from accounts.models import UserBankAccount
from .contants import DEPOSIT, LOAN, LOAN_PAID, WITHDRAWAL, SEND_MONEY, RECEIVE_MONEY, send_mail_to_user
from .forms import DepositForm, WithdrawalForm, LoanRequestForm, SendMoneyForm
# Create your views here.


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    success_url = reverse_lazy("transaction_report")
    title = ''
    model = Transactions

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.title
        return context


class SendMoneyView(TransactionCreateMixin):
    title = "Send money"
    form_class = SendMoneyForm
    template_name = 'transactions/send_money.html'

    def get_initial(self):
        initial = {
            'transaction_type': SEND_MONEY
        }
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        account_no = form.cleaned_data['account_no']

        receiver_account = UserBankAccount.objects.get(account_no=account_no)
        receiver_account.balance += amount
        receiver_account.save(update_fields=['balance'])

        receiver_transaction = Transactions(
            amount=amount, transaction_type=RECEIVE_MONEY, account=receiver_account, balance_after_transaction=receiver_account.balance)
        receiver_transaction.save()

        sender_account = self.request.user.account
        sender_account.balance -= amount
        sender_account.save(update_fields=['balance'])

        sender_email = self.request.user.email
        receiver_email = receiver_account.user.email

        send_mail_to_user("Transfer money", 'transactions/transaction_sender_mail.html', {
            'amount': amount,
            'account_no': account_no,
            'owner': self.request.user
        }, sender_email)

        send_mail_to_user("Transfer money", 'transactions/transaction_receiver_email.html', {
            'amount': amount,
            'account_no': sender_account.account_no,
            'owner': receiver_account.user
        }, receiver_email)

        messages.success(self.request, f"""{amount} has been sent to Account:  {account_no}""")
        return super().form_valid(form)


class DepositMoneyView(TransactionCreateMixin):
    success_url = reverse_lazy("transaction_report")
    title = 'Deposit Money'

    form_class = DepositForm

    def get_initial(self):
        initial = {
            'transaction_type': DEPOSIT
        }
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account

        account.balance += amount
        account.save(update_fields=['balance'])
        messages.success(self.request, f"""{
                         amount} is deposited to your account """)
        return super().form_valid(form)


class WithdrawalMoneyView(TransactionCreateMixin):
    success_url = reverse_lazy("transaction_report")
    title = 'Withdraw Money'

    form_class = WithdrawalForm

    def get_initial(self):
        initial = {
            'transaction_type': WITHDRAWAL
        }
        return initial

    def form_valid(self, form):
        bank = Bank.objects.get(name="Jomuna")
        if not bank.status:
            amount = form.cleaned_data.get('amount')
            account = self.request.user.account

            account.balance -= amount
            account.save(update_fields=['balance'])

            messages.success(self.request, f"""{
                amount} is withdrawn from your account """)
            return super().form_valid(form)
        else:
            messages.error(
                self.request, f"""Can't withdraw money bank is bankrupt""")
            return redirect("homepage")


class LoanMoneyView(TransactionCreateMixin):
    title = 'Request For Loan'

    form_class = LoanRequestForm

    def get_initial(self):
        initial = {
            'transaction_type': LOAN
        }
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        current_loan_count = Transactions.objects.filter(
            account=self.request.user.account, loan_approval=True, transaction_type=LOAN).count()

        if current_loan_count >= 3:
            return HttpResponse("Loan limit exceeded")

        messages.success(self.request, f"""Loan request for {
                         amount} successfully sent""")
        return super().form_valid(form)


class TransactionReportView(LoginRequiredMixin, ListView):
    model = Transactions
    template_name = 'transactions/transaction_report.html'
    balance = 0

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account=self.request.user.account
        )

        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()

            queryset = queryset.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date)

            self.balance = Transactions.objects.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["account"] = self.request.user.account
        return context


class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transactions, id=loan_id)

        if loan.loan_approval:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()
                return redirect('transaction_report')
            else:
                return redirect('transaction_report')


class LoanListView(LoginRequiredMixin, ListView):
    model = Transactions
    template_name = 'transactions/loan_request.html'
    context_object_name = 'loans'

    def get_queryset(self):
        user = self.request.user.account
        queryset = Transactions.objects.filter(
            account=user, transaction_type=LOAN)
        return queryset

transactions/templates/transactions/loan_request.html
{% extends "base.html" %}
{% block head_title %}
    {{ title }}
{% endblock head_title %}
{% block mainContent %}
    <div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
        <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
        <hr />
        <table class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500">
            <thead class="bg-purple-900 text-white text-left">
                <tr class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold">
                    <th class="px-4 py-2">LOAN ID</th>
                    <th class="px-4 py-2">Loan Amount</th>
                    <th class="px-4 py-2">Loan Approved</th>
                    <th class="px-4 py-2">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for loan in loans %}
                    <tr class="border-b dark:border-neutral-500">
                        <td class="px-4 py-2">{{ loan.id }}</td>
                        <td class="px-4 py-3 text-s border">
                            <span class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100">{{ loan.amount }}</span>
                        </td>
                        <td class="px-4 py-2">{{ loan.loan_approval }}</td>
                        <td class="px-4 py-2">
                            {% if loan.loan_approval %}
                                <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg"
                                   href='{% url "pay_loan" loan.id %}'>Pay</a>
                            {% else %}
                                <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock mainContent %}

transactions/templates/transactions/send_money.html
{% extends "base.html" %}
{% block head_title %}
    {{ title }}
{% endblock head_title %}
{% block mainContent %}
    <div class="w-full flex mt-5 justify-center ">
        <div class="bg-white w-5/12 rounded-lg">
            {% if title == 'Request For Loan' %}
                <div>
                    <a class="font-bold text-blue text-center pb-5 pt-10 px-5"
                       href="{% url 'loan_list' %}">View All Loan List</a>
                </div>
            {% endif %}
            <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
            <form method="post" class="px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="account_no">account_no</label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
                           name="account_no"
                           id="account_no"
                           type="number"
                           required
                           placeholder="account_no">
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">Amount</label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
                           name="amount"
                           id="amount"
                           type="number"
                           required
                           placeholder="Amount">
                </div>
                {% if form.amount.errors %}
                    {% for error in form.amount.errors %}<p class="text-red-600 text-sm italic pb-2">{{ error }}</p>{% endfor %}
                {% endif %}
                {% if form.account_no.errors %}
                    {% for error in form.account_no.errors %}<p class="text-red-600 text-sm italic pb-2">{{ error }}</p>{% endfor %}
                {% endif %}
                <div class="flex w-full justify-center">
                    <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg"
                            type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock mainContent %}

transactions/templates/transactions/transaction_form.html
{% extends "base.html" %}
{% block head_title %}
    {{ title }}
{% endblock head_title %}
{% block mainContent %}
    <div class="w-full flex mt-5 justify-center ">
        <div class="bg-white w-5/12 rounded-lg">
            {% if title == 'Request For Loan' %}
                <div>
                    <a class="font-bold text-blue text-center pb-5 pt-10 px-5"
                       href="{% url 'loan_list' %}">View All Loan List</a>
                </div>
            {% endif %}
            <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
            <form method="post" class="px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">Amount</label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
                           name="amount"
                           id="amount"
                           type="number"
                           required
                           placeholder="Amount">
                </div>
                {% if form.amount.errors %}
                    {% for error in form.amount.errors %}<p class="text-red-600 text-sm italic pb-2">{{ error }}</p>{% endfor %}
                {% endif %}
                <div class="flex w-full justify-center">
                    <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg"
                            type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock mainContent %}

transactions/templates/transactions/transaction_report.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block head_title %}
    Transaction Report
{% endblock head_title %}
{% block mainContent %}
    <div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
        <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
        <hr />
        <form method="get" action="{% url 'transaction_report' %}">
            <div class="flex justify-center">
                <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2">
                    <label for="start_date">From:</label>
                    <input class="appearance-none w-full outline-none focus:outline-none active:outline-none"
                           type="date"
                           id="start_date"
                           name="start_date" />
                </div>
                <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12">
                    <label for="end_date">To:</label>
                    <input class="appearance-none w-full outline-none focus:outline-none active:outline-none"
                           type="date"
                           id="end_date"
                           name="end_date" />
                </div>
                <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
                    <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                            type="submit">Filter</button>
                </div>
            </div>
        </form>
        <table class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500">
            <thead class="bg-purple-900 text-white text-left">
                <tr class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold">
                    <th class="px-4 py-2">Date</th>
                    <th class="px-4 py-2">Transaction Type</th>
                    <th class="px-4 py-2">Amount</th>
                    <th class="px-4 py-2">Balance After Transaction</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in object_list %}
                    <tr class="border-b dark:border-neutral-500">
                        <td class="px-4 py-2">{{ transaction.timestamp|date:"F d, Y h:i A" }}</td>
                        <td class="px-4 py-3 text-s border">
                            <span class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}">
                                {{ transaction.get_transaction_type_display }}
                            </span>
                        </td>
                        <td class="px-4 py-2">$ {{ transaction.amount|floatformat:2|intcomma }}</td>
                        <td class="px-4 py-2">$ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}</td>
                    </tr>
                {% endfor %}
                <tr class="bg-gray-800 text-white">
                    <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
                    <th class="px-4 py-2 text-left">$ {{ account.balance|floatformat:2|intcomma }}</th>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock mainContent %}

transactions/templates/transactions/transaction_sender_mail.html
<h1>Hi {{ owner.username }}</h1>
<h4 style="color: red;">Money transfer alert</h4>
<p>
    A transaction has been made from your account.
    <b>{{ amount }}tk</b> has been transferred to <b>{{ account_no }}</b>.
</p>
<p>
    Best regards
    Mamar bank
</p>